// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recommender.Data;

namespace recommender.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("recommender.Services.BookService", b =>
                {
                    b.ToTable("Books");
                });

            modelBuilder.Entity("recommender.Services.RatingService", b =>
                {
                    b.ToTable("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
